{{#LICENSE}}
{{!===----------------------------------------------------------------------===}}
{{!                                                                            }}
{{! Part of the Utopia EDA Project, under the Apache License v2.0              }}
{{! SPDX-License-Identifier: Apache-2.0                                        }}
{{! Copyright 2022 ISP RAS (http://www.ispras.ru)                              }}
{{!                                                                            }}
{{!===----------------------------------------------------------------------===}}
{{/LICENSE}}/*
 * This Verilog library file was automatically generated by Utopia EDA
 * Generation started: {{GEN_TIME}}
 *
 * Ivannikov Institute for System Programming
 * of the Russian Academy of Sciences (ISP RAS)
 * 25 Alexander Solzhenitsyn st., Moscow, 109004, Russia
 * http://forge.ispras.ru/projects/utopia
 */

	// inputs
{{#INS}}input  {{IN_TYPE}} {{IN_NAME}};
{{/INS}}
	// outputs
{{#OUTS}}output  {{OUT_TYPE}}{{OUT_NAME}}
{{/OUTS}});

@(*) {
{{BODY}}
}

