{{#LICENSE}}
{{!===----------------------------------------------------------------------===}}
{{!                                                                            }}
{{! Part of the Utopia EDA Project, under the Apache License v2.0              }}
{{! SPDX-License-Identifier: Apache-2.0                                        }}
{{! Copyright 2021 ISP RAS (http://www.ispras.ru)                              }}
{{!                                                                            }}
{{!===----------------------------------------------------------------------===}}
{{/LICENSE}}/*
 * This Verilog testbench was automatically generated by Utopia EDA
 * Generation started: {{GEN_TIME}}
 *
 * Ivannikov Institute for System Programming
 * of the Russian Academy of Sciences (ISP RAS)
 * 25 Alexander Solzhenitsyn st., Moscow, 109004, Russia
 * http://forge.ispras.ru/projects/utopia
 */

module {{MODULE_NAME}}(
	// inputs
{{#INS}}	{{IN_NAME}}{{IN_SEP}}
{{/INS}}
	// outputs
{{#OUTS}}	{{OUT_NAME}}{{OUT_SEP}}
{{/OUTS}});

{{BODY}}
endmodule // {{MODULE_NAME}}
