{{#LICENSE}}
{{!===---------------------------------------------------------------------===}}
{{!                                                                           }}
{{! Part of the Utopia EDA Project, under the Apache License v2.0             }}
{{! SPDX-License-Identifier: Apache-2.0                                       }}
{{! Copyright 2023 ISP RAS (http://www.ispras.ru)                             }}
{{!                                                                           }}
{{!===---------------------------------------------------------------------===}}
{{/LICENSE}}/*
 * This Verilog file was automatically generated by Utopia EDA
 * Generation started: {{GEN_TIME}}
 *
 * Ivannikov Institute for System Programming
 * of the Russian Academy of Sciences (ISP RAS)
 * 25 Alexander Solzhenitsyn st., Moscow, 109004, Russia
 * http://forge.ispras.ru/projects/utopia
 */

module {{MODULE_NAME}} (
// inputs
{{#INS}}input {{INPUT}}{{SEP}}
{{/INS}}
// outputs
{{#OUTS}}output	{{OUTPUT}}{{SEP}}
{{/OUTS}});
// wires
{{#WIRES}}wire {{WIRE_NAME}};
{{/WIRES}}
// assignments
{{#ASSIGNS}}assign {{LHS}} = {{RHS}};
{{/ASSIGNS}}
// gates
{{#GATES}}{{GATE_NAME}} {{GATE_TYPE}}({{GATE_OUT}},{{#G_INS}} {{GATE_IN}}{{SEP}}{{/G_INS}});
{{/GATES}}

endmodule // {{MODULE_NAME}}
