{{#LICENSE}}
{{!===----------------------------------------------------------------------===}}
{{!                                                                            }}
{{! Part of the Utopia EDA Project, under the Apache License v2.0              }}
{{! SPDX-License-Identifier: Apache-2.0                                        }}
{{! Copyright 2022 ISP RAS (http://www.ispras.ru)                              }}
{{!                                                                            }}
{{!===----------------------------------------------------------------------===}}
{{/LICENSE}}
// This MLIR FIRRTL DIALECT top module was automatically generated by Utopia EDA
// Generation started: {{GEN_TIME}}
 
// Ivannikov Institute for System Programming
// of the Russian Academy of Sciences (ISP RAS)
// 25 Alexander Solzhenitsyn st., Moscow, 109004, Russia
// http://forge.ispras.ru/projects/utopia

firrtl.circuit "{{CIRCUIT_NAME}}" {
    firrtl.module @{{CIRCUIT_NAME}} (
{{#TOP_INS}}    in %{{TOP_IN_NAME}} : !firrtl.{{TOP_IN_TYPE}}{{TOP_IN_SEP}}
{{/TOP_INS}}
{{#TOP_OUTS}}    out %{{TOP_OUT_NAME}} : !firrtl.{{TOP_OUT_TYPE}}{{TOP_OUT_SEP}}
{{/TOP_OUTS}})
    {
    // Instances
    {{#INSTS}}{{#INST_INS}}%{{INST_IN_NAME}}{{INST_IN_SEP}} {{/INST_INS}} {{#INST_OUTS}}%{{INST_OUT_NAME}}{{INST_OUT_SEP}} {{/INST_OUTS}}= firrtl.instance {{INSTANCE_NAME}} @{{MODULE_NAME}}({{#MODULE_INS}}in {{MOD_IN_NAME}} : !firrtl.{{MOD_IN_TYPE}}{{MOD_IN_SEP}} {{/MODULE_INS}}{{#MODULE_OUTS}}out {{MOD_OUT_NAME}} : !firrtl.{{MOD_OUT_TYPE}}{{MOD_OUT_SEP}} {{/MODULE_OUTS}})
    {{/INSTS}}
    // Connections
    {{#CONS}}firrtl.connect %{{CON_OUT_NAME}}, %{{CON_IN_NAME}} : !firrtl.{{CON_OUT_TYPE}}, !firrtl.{{CON_IN_TYPE}}
    {{/CONS}}
    }
    // External modules declaration
    {{#EXTS}}firrtl.extmodule @{{EXTMODULE_NAME}}(
    {{#EXT_INS}}    in {{EXT_IN_NAME}} : !firrtl.{{EXT_IN_TYPE}}{{EXT_IN_SEP}}
    {{/EXT_INS}}
    {{#EXT_OUTS}}    out {{EXT_OUT_NAME}} : !firrtl.{{EXT_OUT_TYPE}}{{EXT_OUT_SEP}}
    {{/EXT_OUTS}}
    )
    {{/EXTS}}
}
