/*
 * This Verilog library file was automatically generated by Utopia EDA
 * Generation started: 7-2-2023 0:51:29
 *
 * Ivannikov Institute for System Programming
 * of the Russian Academy of Sciences (ISP RAS)
 * 25 Alexander Solzhenitsyn st., Moscow, 109004, Russia
 * http://forge.ispras.ru/projects/utopia
 */

module kernel1(
	// inputs
	clock,
	reset,
	x,
	y,

	// outputs
	z
);


input clock;
input reset;
input x;
input y;
output z;
wire x;
wire y;
wire z;
reg [1:0] state_0;
always @(posedge clock) begin
state_0 <= {x, y};
end
assign z = state_0[0:0];

endmodule // kernel1
/*
 * This Verilog library file was automatically generated by Utopia EDA
 * Generation started: 7-2-2023 0:51:29
 *
 * Ivannikov Institute for System Programming
 * of the Russian Academy of Sciences (ISP RAS)
 * 25 Alexander Solzhenitsyn st., Moscow, 109004, Russia
 * http://forge.ispras.ru/projects/utopia
 */

module kernel2(
	// inputs
	clock,
	reset,
	z,

	// outputs
	w,
	y
);


input clock;
input reset;
input z;
output w;
output y;
wire z;
wire w;
wire y;
reg [0:0] state_0;
always @(posedge clock) begin
state_0 <= {z};
end
assign w = state_0[0:0];
assign y = state_0[0:0];

endmodule // kernel2
/*
 * This Verilog library file was automatically generated by Utopia EDA
 * Generation started: 7-2-2023 0:51:29
 *
 * Ivannikov Institute for System Programming
 * of the Russian Academy of Sciences (ISP RAS)
 * 25 Alexander Solzhenitsyn st., Moscow, 109004, Russia
 * http://forge.ispras.ru/projects/utopia
 */

module sink(
	// inputs
	clock,
	reset,
	w

	// outputs
);


input clock;
input reset;
input w;
wire w;

endmodule // sink
/*
 * This Verilog library file was automatically generated by Utopia EDA
 * Generation started: 7-2-2023 0:51:29
 *
 * Ivannikov Institute for System Programming
 * of the Russian Academy of Sciences (ISP RAS)
 * 25 Alexander Solzhenitsyn st., Moscow, 109004, Russia
 * http://forge.ispras.ru/projects/utopia
 */

module source(
	// inputs
	clock,
	reset,

	// outputs
	x
);


input clock;
input reset;
output x;
wire x;

endmodule // source
