
// This MLIR FIRRTL DIALECT top module was automatically generated by Utopia EDA
// Generation started: 7-2-2023 0:51:29
 
// Ivannikov Institute for System Programming
// of the Russian Academy of Sciences (ISP RAS)
// 25 Alexander Solzhenitsyn st., Moscow, 109004, Russia
// http://forge.ispras.ru/projects/utopia

firrtl.circuit "main" {
    firrtl.module @main (
    in %clock : !firrtl.clock,
    in %reset : !firrtl.reset,
    in %n1_x : !firrtl.sint<1>,

    out %n4_w : !firrtl.sint<1>
)
    {
    // Instances
    %n2_clock, %n2_reset, %n2_x, %n2_y,  %n2_z = firrtl.instance n2 @kernel1(in clock : !firrtl.clock, in reset : !firrtl.reset, in x : !firrtl.sint<1>, in y : !firrtl.sint<1>, out z : !firrtl.sint<1> )
    %n3_clock, %n3_reset, %n3_z,  %n3_w, %n3_y = firrtl.instance n3 @kernel2(in clock : !firrtl.clock, in reset : !firrtl.reset, in z : !firrtl.sint<1>, out w : !firrtl.sint<1>, out y : !firrtl.sint<1> )
    
    // Connections
    firrtl.connect %n2_clock, %clock : !firrtl.clock, !firrtl.clock
    firrtl.connect %n2_reset, %reset : !firrtl.reset, !firrtl.reset
    firrtl.connect %n2_x, %n1_x : !firrtl.sint<1>, !firrtl.sint<1>
    firrtl.connect %n3_z, %n2_z : !firrtl.sint<1>, !firrtl.sint<1>
    firrtl.connect %n3_clock, %clock : !firrtl.clock, !firrtl.clock
    firrtl.connect %n3_reset, %reset : !firrtl.reset, !firrtl.reset
    firrtl.connect %n4_w, %n3_w : !firrtl.sint<1>, !firrtl.sint<1>
    firrtl.connect %n2_y, %n3_y : !firrtl.sint<1>, !firrtl.sint<1>
    
    }
    // External modules declaration
    firrtl.extmodule @kernel1(
        in clock : !firrtl.clock,
        in reset : !firrtl.reset,
        in x : !firrtl.sint<1>,
        in y : !firrtl.sint<1>,
    
        out z : !firrtl.sint<1>
    
    )
    firrtl.extmodule @kernel2(
        in clock : !firrtl.clock,
        in reset : !firrtl.reset,
        in z : !firrtl.sint<1>,
    
        out w : !firrtl.sint<1>,
        out y : !firrtl.sint<1>
    
    )
    firrtl.extmodule @sink(
        in clock : !firrtl.clock,
        in reset : !firrtl.reset,
        in w : !firrtl.sint<1>
    
    
    )
    firrtl.extmodule @source(
        in clock : !firrtl.clock,
        in reset : !firrtl.reset,
    
        out x : !firrtl.sint<1>
    
    )
    
}
