/*
 * This Verilog library file was automatically generated by Utopia EDA
 * Generation started: 29-1-2023 8:52:56
 *
 * Ivannikov Institute for System Programming
 * of the Russian Academy of Sciences (ISP RAS)
 * 25 Alexander Solzhenitsyn st., Moscow, 109004, Russia
 * http://forge.ispras.ru/projects/utopia
 */

module ADD_2x1(
	// inputs
	clock,
	reset,
	_dfc_wire_4824,
	_dfc_wire_4828,

	// outputs
	_dfc_wire_4836
);


input clock;
input reset;
input [15:0] _dfc_wire_4824;
input [15:0] _dfc_wire_4828;
output [15:0] _dfc_wire_4836;
wire [15:0] _dfc_wire_4824;
wire [15:0] _dfc_wire_4828;
wire [15:0] _dfc_wire_4836;
assign {_dfc_wire_4836} = $signed(_dfc_wire_4824) + $signed(_dfc_wire_4828);

endmodule // ADD_2x1
/*
 * This Verilog library file was automatically generated by Utopia EDA
 * Generation started: 29-1-2023 8:52:56
 *
 * Ivannikov Institute for System Programming
 * of the Russian Academy of Sciences (ISP RAS)
 * 25 Alexander Solzhenitsyn st., Moscow, 109004, Russia
 * http://forge.ispras.ru/projects/utopia
 */

module delay_fixed_16_0_1_2(
	// inputs
	clock,
	reset,
	in,

	// outputs
	out
);


input clock;
input reset;
input [15:0] in;
output [15:0] out;
wire [15:0] in;
reg [15:0] out;
reg [31:0] state;
reg [31:0] s0;
reg [31:0] s1;
reg [31:0] s2;
always @(posedge clock) begin
if (!reset) begin
  state <= 0; end
else if (state == 0) begin
  state <= 1;
  s0 <= in; end
else if (state == 1) begin
  state <= 2;
  s1 <= s0; end
else if (state == 2) begin
  state <= 3;
  s2 <= s1; end
else begin
  state <= 0;
  out <= s2; end
end

endmodule // delay_fixed_16_0_1_2
/*
 * This Verilog library file was automatically generated by Utopia EDA
 * Generation started: 29-1-2023 8:52:56
 *
 * Ivannikov Institute for System Programming
 * of the Russian Academy of Sciences (ISP RAS)
 * 25 Alexander Solzhenitsyn st., Moscow, 109004, Russia
 * http://forge.ispras.ru/projects/utopia
 */

module delay_fixed_16_0_1_21(
	// inputs
	clock,
	reset,
	in,

	// outputs
	out
);


input clock;
input reset;
input [15:0] in;
output [15:0] out;
wire [15:0] in;
reg [15:0] out;
reg [31:0] state;
reg [31:0] s0;
reg [31:0] s1;
reg [31:0] s2;
always @(posedge clock) begin
if (!reset) begin
  state <= 0; end
else if (state == 0) begin
  state <= 1;
  s0 <= in; end
else if (state == 1) begin
  state <= 2;
  s1 <= s0; end
else if (state == 2) begin
  state <= 3;
  s2 <= s1; end
else begin
  state <= 0;
  out <= s2; end
end

endmodule // delay_fixed_16_0_1_21
/*
 * This Verilog library file was automatically generated by Utopia EDA
 * Generation started: 29-1-2023 8:52:56
 *
 * Ivannikov Institute for System Programming
 * of the Russian Academy of Sciences (ISP RAS)
 * 25 Alexander Solzhenitsyn st., Moscow, 109004, Russia
 * http://forge.ispras.ru/projects/utopia
 */

module delay_fixed_16_0_1_39(
	// inputs
	clock,
	reset,
	in,

	// outputs
	out
);


input clock;
input reset;
input [15:0] in;
output [15:0] out;
wire [15:0] in;
reg [15:0] out;
reg [31:0] state;
reg [31:0] s0;
reg [31:0] s1;
reg [31:0] s2;
always @(posedge clock) begin
if (!reset) begin
  state <= 0; end
else if (state == 0) begin
  state <= 1;
  s0 <= in; end
else if (state == 1) begin
  state <= 2;
  s1 <= s0; end
else if (state == 2) begin
  state <= 3;
  s2 <= s1; end
else begin
  state <= 0;
  out <= s2; end
end

endmodule // delay_fixed_16_0_1_39
/*
 * This Verilog library file was automatically generated by Utopia EDA
 * Generation started: 29-1-2023 8:52:56
 *
 * Ivannikov Institute for System Programming
 * of the Russian Academy of Sciences (ISP RAS)
 * 25 Alexander Solzhenitsyn st., Moscow, 109004, Russia
 * http://forge.ispras.ru/projects/utopia
 */

module delay_fixed_16_0_1_49(
	// inputs
	clock,
	reset,
	in,

	// outputs
	out
);


input clock;
input reset;
input [15:0] in;
output [15:0] out;
wire [15:0] in;
reg [15:0] out;
reg [31:0] state;
reg [31:0] s0;
reg [31:0] s1;
reg [31:0] s2;
always @(posedge clock) begin
if (!reset) begin
  state <= 0; end
else if (state == 0) begin
  state <= 1;
  s0 <= in; end
else if (state == 1) begin
  state <= 2;
  s1 <= s0; end
else if (state == 2) begin
  state <= 3;
  s2 <= s1; end
else begin
  state <= 0;
  out <= s2; end
end

endmodule // delay_fixed_16_0_1_49
/*
 * This Verilog library file was automatically generated by Utopia EDA
 * Generation started: 29-1-2023 8:52:56
 *
 * Ivannikov Institute for System Programming
 * of the Russian Academy of Sciences (ISP RAS)
 * 25 Alexander Solzhenitsyn st., Moscow, 109004, Russia
 * http://forge.ispras.ru/projects/utopia
 */

module sink_1x0(
	// inputs
	clock,
	reset,
	_dfc_wire_4848

	// outputs
);


input clock;
input reset;
input [15:0] _dfc_wire_4848;
wire [15:0] _dfc_wire_4848;

endmodule // sink_1x0
/*
 * This Verilog library file was automatically generated by Utopia EDA
 * Generation started: 29-1-2023 8:52:56
 *
 * Ivannikov Institute for System Programming
 * of the Russian Academy of Sciences (ISP RAS)
 * 25 Alexander Solzhenitsyn st., Moscow, 109004, Russia
 * http://forge.ispras.ru/projects/utopia
 */

module source_0x1(
	// inputs
	clock,
	reset,

	// outputs
	_dfc_wire_4825
);


input clock;
input reset;
output [15:0] _dfc_wire_4825;
wire [15:0] _dfc_wire_4825;

endmodule // source_0x1
