
// This MLIR FIRRTL DIALECT top module was automatically generated by Utopia EDA
// Generation started: 7-2-2023 0:51:36
 
// Ivannikov Institute for System Programming
// of the Russian Academy of Sciences (ISP RAS)
// 25 Alexander Solzhenitsyn st., Moscow, 109004, Russia
// http://forge.ispras.ru/projects/utopia

firrtl.circuit "VectorSum" {
    firrtl.module @VectorSum (
    in %clock : !firrtl.clock,
    in %reset : !firrtl.reset,
    in %source__dfc_wire_4825__dfc_wire_4825 : !firrtl.sint<16>,
    in %source__dfc_wire_4826__dfc_wire_4825 : !firrtl.sint<16>,
    in %source__dfc_wire_4830__dfc_wire_4825 : !firrtl.sint<16>,
    in %source__dfc_wire_4824__dfc_wire_4825 : !firrtl.sint<16>,
    in %source__dfc_wire_4827__dfc_wire_4825 : !firrtl.sint<16>,
    in %source__dfc_wire_4831__dfc_wire_4825 : !firrtl.sint<16>,
    in %source__dfc_wire_4828__dfc_wire_4825 : !firrtl.sint<16>,
    in %source__dfc_wire_4829__dfc_wire_4825 : !firrtl.sint<16>,

    out %sink__dfc_wire_4848__dfc_wire_4848 : !firrtl.sint<16>,
    out %sink__dfc_wire_4840__dfc_wire_4848 : !firrtl.sint<16>,
    out %sink__dfc_wire_4844__dfc_wire_4848 : !firrtl.sint<16>,
    out %sink__dfc_wire_4836__dfc_wire_4848 : !firrtl.sint<16>
)
    {
    // Instances
    %ADD2150_clock, %ADD2150_reset, %ADD2150__dfc_wire_4824, %ADD2150__dfc_wire_4828,  %ADD2150__dfc_wire_4836 = firrtl.instance ADD2150 @ADD_2x1(in clock : !firrtl.clock, in reset : !firrtl.reset, in _dfc_wire_4824 : !firrtl.sint<16>, in _dfc_wire_4828 : !firrtl.sint<16>, out _dfc_wire_4836 : !firrtl.sint<16> )
    %ADD2151_clock, %ADD2151_reset, %ADD2151__dfc_wire_4824, %ADD2151__dfc_wire_4828,  %ADD2151__dfc_wire_4836 = firrtl.instance ADD2151 @ADD_2x1(in clock : !firrtl.clock, in reset : !firrtl.reset, in _dfc_wire_4824 : !firrtl.sint<16>, in _dfc_wire_4828 : !firrtl.sint<16>, out _dfc_wire_4836 : !firrtl.sint<16> )
    %ADD2152_clock, %ADD2152_reset, %ADD2152__dfc_wire_4824, %ADD2152__dfc_wire_4828,  %ADD2152__dfc_wire_4836 = firrtl.instance ADD2152 @ADD_2x1(in clock : !firrtl.clock, in reset : !firrtl.reset, in _dfc_wire_4824 : !firrtl.sint<16>, in _dfc_wire_4828 : !firrtl.sint<16>, out _dfc_wire_4836 : !firrtl.sint<16> )
    %ADD2153_clock, %ADD2153_reset, %ADD2153__dfc_wire_4824, %ADD2153__dfc_wire_4828,  %ADD2153__dfc_wire_4836 = firrtl.instance ADD2153 @ADD_2x1(in clock : !firrtl.clock, in reset : !firrtl.reset, in _dfc_wire_4824 : !firrtl.sint<16>, in _dfc_wire_4828 : !firrtl.sint<16>, out _dfc_wire_4836 : !firrtl.sint<16> )
    %delay_fixed_16_0_1_1_16_clock, %delay_fixed_16_0_1_1_16_reset, %delay_fixed_16_0_1_1_16_in,  %delay_fixed_16_0_1_1_16_out = firrtl.instance delay_fixed_16_0_1_1_16 @delay_fixed_16_0_1_1(in clock : !firrtl.clock, in reset : !firrtl.reset, in in : !firrtl.sint<16>, out out : !firrtl.sint<16> )
    %delay_fixed_16_0_1_32_17_clock, %delay_fixed_16_0_1_32_17_reset, %delay_fixed_16_0_1_32_17_in,  %delay_fixed_16_0_1_32_17_out = firrtl.instance delay_fixed_16_0_1_32_17 @delay_fixed_16_0_1_32(in clock : !firrtl.clock, in reset : !firrtl.reset, in in : !firrtl.sint<16>, out out : !firrtl.sint<16> )
    %delay_fixed_16_0_1_21_18_clock, %delay_fixed_16_0_1_21_18_reset, %delay_fixed_16_0_1_21_18_in,  %delay_fixed_16_0_1_21_18_out = firrtl.instance delay_fixed_16_0_1_21_18 @delay_fixed_16_0_1_21(in clock : !firrtl.clock, in reset : !firrtl.reset, in in : !firrtl.sint<16>, out out : !firrtl.sint<16> )
    %delay_fixed_16_0_1_59_19_clock, %delay_fixed_16_0_1_59_19_reset, %delay_fixed_16_0_1_59_19_in,  %delay_fixed_16_0_1_59_19_out = firrtl.instance delay_fixed_16_0_1_59_19 @delay_fixed_16_0_1_59(in clock : !firrtl.clock, in reset : !firrtl.reset, in in : !firrtl.sint<16>, out out : !firrtl.sint<16> )
    
    // Connections
    firrtl.connect %ADD2150_clock, %clock : !firrtl.clock, !firrtl.clock
    firrtl.connect %ADD2150_reset, %reset : !firrtl.reset, !firrtl.reset
    firrtl.connect %ADD2150__dfc_wire_4828, %source__dfc_wire_4828__dfc_wire_4825 : !firrtl.sint<16>, !firrtl.sint<16>
    firrtl.connect %sink__dfc_wire_4836__dfc_wire_4848, %ADD2150__dfc_wire_4836 : !firrtl.sint<16>, !firrtl.sint<16>
    firrtl.connect %ADD2151_clock, %clock : !firrtl.clock, !firrtl.clock
    firrtl.connect %ADD2151_reset, %reset : !firrtl.reset, !firrtl.reset
    firrtl.connect %ADD2151__dfc_wire_4828, %source__dfc_wire_4829__dfc_wire_4825 : !firrtl.sint<16>, !firrtl.sint<16>
    firrtl.connect %sink__dfc_wire_4840__dfc_wire_4848, %ADD2151__dfc_wire_4836 : !firrtl.sint<16>, !firrtl.sint<16>
    firrtl.connect %ADD2152_clock, %clock : !firrtl.clock, !firrtl.clock
    firrtl.connect %ADD2152_reset, %reset : !firrtl.reset, !firrtl.reset
    firrtl.connect %ADD2152__dfc_wire_4828, %source__dfc_wire_4830__dfc_wire_4825 : !firrtl.sint<16>, !firrtl.sint<16>
    firrtl.connect %sink__dfc_wire_4844__dfc_wire_4848, %ADD2152__dfc_wire_4836 : !firrtl.sint<16>, !firrtl.sint<16>
    firrtl.connect %ADD2153_clock, %clock : !firrtl.clock, !firrtl.clock
    firrtl.connect %ADD2153_reset, %reset : !firrtl.reset, !firrtl.reset
    firrtl.connect %ADD2153__dfc_wire_4824, %source__dfc_wire_4827__dfc_wire_4825 : !firrtl.sint<16>, !firrtl.sint<16>
    firrtl.connect %sink__dfc_wire_4848__dfc_wire_4848, %ADD2153__dfc_wire_4836 : !firrtl.sint<16>, !firrtl.sint<16>
    firrtl.connect %delay_fixed_16_0_1_1_16_clock, %clock : !firrtl.clock, !firrtl.clock
    firrtl.connect %delay_fixed_16_0_1_1_16_reset, %reset : !firrtl.reset, !firrtl.reset
    firrtl.connect %delay_fixed_16_0_1_1_16_in, %source__dfc_wire_4831__dfc_wire_4825 : !firrtl.sint<16>, !firrtl.sint<16>
    firrtl.connect %ADD2153__dfc_wire_4828, %delay_fixed_16_0_1_1_16_out : !firrtl.sint<16>, !firrtl.sint<16>
    firrtl.connect %delay_fixed_16_0_1_32_17_clock, %clock : !firrtl.clock, !firrtl.clock
    firrtl.connect %delay_fixed_16_0_1_32_17_reset, %reset : !firrtl.reset, !firrtl.reset
    firrtl.connect %delay_fixed_16_0_1_32_17_in, %source__dfc_wire_4826__dfc_wire_4825 : !firrtl.sint<16>, !firrtl.sint<16>
    firrtl.connect %ADD2152__dfc_wire_4824, %delay_fixed_16_0_1_32_17_out : !firrtl.sint<16>, !firrtl.sint<16>
    firrtl.connect %delay_fixed_16_0_1_21_18_clock, %clock : !firrtl.clock, !firrtl.clock
    firrtl.connect %delay_fixed_16_0_1_21_18_reset, %reset : !firrtl.reset, !firrtl.reset
    firrtl.connect %delay_fixed_16_0_1_21_18_in, %source__dfc_wire_4825__dfc_wire_4825 : !firrtl.sint<16>, !firrtl.sint<16>
    firrtl.connect %ADD2151__dfc_wire_4824, %delay_fixed_16_0_1_21_18_out : !firrtl.sint<16>, !firrtl.sint<16>
    firrtl.connect %delay_fixed_16_0_1_59_19_clock, %clock : !firrtl.clock, !firrtl.clock
    firrtl.connect %delay_fixed_16_0_1_59_19_reset, %reset : !firrtl.reset, !firrtl.reset
    firrtl.connect %delay_fixed_16_0_1_59_19_in, %source__dfc_wire_4824__dfc_wire_4825 : !firrtl.sint<16>, !firrtl.sint<16>
    firrtl.connect %ADD2150__dfc_wire_4824, %delay_fixed_16_0_1_59_19_out : !firrtl.sint<16>, !firrtl.sint<16>
    
    }
    // External modules declaration
    firrtl.extmodule @ADD_2x1(
        in clock : !firrtl.clock,
        in reset : !firrtl.reset,
        in _dfc_wire_4824 : !firrtl.sint<16>,
        in _dfc_wire_4828 : !firrtl.sint<16>,
    
        out _dfc_wire_4836 : !firrtl.sint<16>
    
    )
    firrtl.extmodule @delay_fixed_16_0_1_1(
        in clock : !firrtl.clock,
        in reset : !firrtl.reset,
        in in : !firrtl.sint<16>,
    
        out out : !firrtl.sint<16>
    
    )
    firrtl.extmodule @delay_fixed_16_0_1_21(
        in clock : !firrtl.clock,
        in reset : !firrtl.reset,
        in in : !firrtl.sint<16>,
    
        out out : !firrtl.sint<16>
    
    )
    firrtl.extmodule @delay_fixed_16_0_1_32(
        in clock : !firrtl.clock,
        in reset : !firrtl.reset,
        in in : !firrtl.sint<16>,
    
        out out : !firrtl.sint<16>
    
    )
    firrtl.extmodule @delay_fixed_16_0_1_59(
        in clock : !firrtl.clock,
        in reset : !firrtl.reset,
        in in : !firrtl.sint<16>,
    
        out out : !firrtl.sint<16>
    
    )
    firrtl.extmodule @sink_1x0(
        in clock : !firrtl.clock,
        in reset : !firrtl.reset,
        in _dfc_wire_4848 : !firrtl.sint<16>
    
    
    )
    firrtl.extmodule @source_0x1(
        in clock : !firrtl.clock,
        in reset : !firrtl.reset,
    
        out _dfc_wire_4825 : !firrtl.sint<16>
    
    )
    
}
