{{#LICENSE}}
{{!===---------------------------------------------------------------------===}}
{{!                                                                           }}
{{! Part of the Utopia HLS Project, under the Apache License v2.0             }}
{{! SPDX-License-Identifier: Apache-2.0                                       }}
{{! Copyright 2021-2024 ISP RAS (http://www.ispras.ru)                        }}
{{!                                                                           }}
{{!===---------------------------------------------------------------------===}}
{{/LICENSE}}
// This file has been automatically generated by Utopia HLS.

{{#FIFO_MODULES}}module {{MODULE_NAME}} (
input [{{WIDTH}}:0] {{ARG1}}, output [{{WIDTH}}:0] {{RES1}}, input {{CLK}});

  reg [{{WIDTH}}:0] r[{{LATENCY}}:0];

  integer i;
  always @ (posedge {{CLK}}) begin
    for (i = {{LATENCY}}; i != 0; i = i - 1) begin
      r[i] <= r[i - 1];
    end
    r[0] <= {{ARG1}};
  end
  assign {{RES1}} = r[{{LATENCY}}];
endmodule // {{MODULE_NAME}}

{{/FIFO_MODULES}}
{{#BINARY_MODULES}}module {{MODULE_NAME}} (
input [{{WIDTH1}}:0] {{ARG1}}, input [{{WIDTH2}}:0] {{ARG2}}, output [{{WIDTH3}}:0] {{RES1}}, input {{CLK}});

  reg [{{RWIDTH}}:0] r[{{LATENCY}}:0];
  reg [{{CAT}}:0] cat;

  integer i;
  always @ (posedge {{CLK}}) begin
    for (i = {{LATENCY}}; i != 0; i = i - 1) begin
      r[i] <= r[i - 1];
    end
    r[0] <= {{{{REPEAT1}}{{{REPEAT_VAL1}}}}, {{ARG1}}} {{OP}} {{{{REPEAT2}}{{{REPEAT_VAL2}}}}, {{ARG2}}};
  end
  assign cat = {{{{REPEAT3}}{{{REPEAT_VAL3}}}}, r[{{LATENCY}}]};
  assign {{RES1}} = cat[{{DIFF}}:0];
endmodule // {{MODULE_NAME}}

{{/BINARY_MODULES}}
