/*
 * This Verilog library file was automatically generated by Utopia EDA
 * Generation started: 7-2-2023 0:51:36
 *
 * Ivannikov Institute for System Programming
 * of the Russian Academy of Sciences (ISP RAS)
 * 25 Alexander Solzhenitsyn st., Moscow, 109004, Russia
 * http://forge.ispras.ru/projects/utopia
 */

module ADD_2x1(
	// inputs
	clock,
	reset,
	_dfc_wire_4859,
	_dfc_wire_4863,

	// outputs
	_dfc_wire_4866
);


input clock;
input reset;
input [15:0] _dfc_wire_4859;
input [15:0] _dfc_wire_4863;
output [15:0] _dfc_wire_4866;
wire [15:0] _dfc_wire_4859;
wire [15:0] _dfc_wire_4863;
wire [15:0] _dfc_wire_4866;
assign {_dfc_wire_4866} = $signed(_dfc_wire_4859) + $signed(_dfc_wire_4863);

endmodule // ADD_2x1
/*
 * This Verilog library file was automatically generated by Utopia EDA
 * Generation started: 7-2-2023 0:51:36
 *
 * Ivannikov Institute for System Programming
 * of the Russian Academy of Sciences (ISP RAS)
 * 25 Alexander Solzhenitsyn st., Moscow, 109004, Russia
 * http://forge.ispras.ru/projects/utopia
 */

module MUL_2x1(
	// inputs
	clock,
	reset,
	_dfc_wire_4852,
	_dfc_wire_4855,

	// outputs
	_dfc_wire_4859
);


input clock;
input reset;
input [15:0] _dfc_wire_4852;
input [15:0] _dfc_wire_4855;
output [15:0] _dfc_wire_4859;
wire [15:0] _dfc_wire_4852;
wire [15:0] _dfc_wire_4855;
wire [15:0] _dfc_wire_4859;
assign {_dfc_wire_4859} = $signed(_dfc_wire_4852) * $signed(_dfc_wire_4855);

endmodule // MUL_2x1
/*
 * This Verilog library file was automatically generated by Utopia EDA
 * Generation started: 7-2-2023 0:51:36
 *
 * Ivannikov Institute for System Programming
 * of the Russian Academy of Sciences (ISP RAS)
 * 25 Alexander Solzhenitsyn st., Moscow, 109004, Russia
 * http://forge.ispras.ru/projects/utopia
 */

module delay_fixed_16_0_1_11(
	// inputs
	clock,
	reset,
	in,

	// outputs
	out
);


input clock;
input reset;
input [15:0] in;
output [15:0] out;
wire [15:0] in;
reg [15:0] out;
reg [31:0] state;
reg [31:0] s0;
reg [31:0] s1;
reg [31:0] s2;
always @(posedge clock) begin
if (!reset) begin
  state <= 0; end
else if (state == 0) begin
  state <= 1;
  s0 <= in; end
else if (state == 1) begin
  state <= 2;
  s1 <= s0; end
else if (state == 2) begin
  state <= 3;
  s2 <= s1; end
else begin
  state <= 0;
  out <= s2; end
end

endmodule // delay_fixed_16_0_1_11
/*
 * This Verilog library file was automatically generated by Utopia EDA
 * Generation started: 7-2-2023 0:51:36
 *
 * Ivannikov Institute for System Programming
 * of the Russian Academy of Sciences (ISP RAS)
 * 25 Alexander Solzhenitsyn st., Moscow, 109004, Russia
 * http://forge.ispras.ru/projects/utopia
 */

module delay_fixed_16_0_1_22(
	// inputs
	clock,
	reset,
	in,

	// outputs
	out
);


input clock;
input reset;
input [15:0] in;
output [15:0] out;
wire [15:0] in;
reg [15:0] out;
reg [31:0] state;
reg [31:0] s0;
reg [31:0] s1;
reg [31:0] s2;
always @(posedge clock) begin
if (!reset) begin
  state <= 0; end
else if (state == 0) begin
  state <= 1;
  s0 <= in; end
else if (state == 1) begin
  state <= 2;
  s1 <= s0; end
else if (state == 2) begin
  state <= 3;
  s2 <= s1; end
else begin
  state <= 0;
  out <= s2; end
end

endmodule // delay_fixed_16_0_1_22
/*
 * This Verilog library file was automatically generated by Utopia EDA
 * Generation started: 7-2-2023 0:51:36
 *
 * Ivannikov Institute for System Programming
 * of the Russian Academy of Sciences (ISP RAS)
 * 25 Alexander Solzhenitsyn st., Moscow, 109004, Russia
 * http://forge.ispras.ru/projects/utopia
 */

module delay_fixed_16_0_1_25(
	// inputs
	clock,
	reset,
	in,

	// outputs
	out
);


input clock;
input reset;
input [15:0] in;
output [15:0] out;
wire [15:0] in;
reg [15:0] out;
reg [31:0] state;
reg [31:0] s0;
reg [31:0] s1;
reg [31:0] s2;
always @(posedge clock) begin
if (!reset) begin
  state <= 0; end
else if (state == 0) begin
  state <= 1;
  s0 <= in; end
else if (state == 1) begin
  state <= 2;
  s1 <= s0; end
else if (state == 2) begin
  state <= 3;
  s2 <= s1; end
else begin
  state <= 0;
  out <= s2; end
end

endmodule // delay_fixed_16_0_1_25
/*
 * This Verilog library file was automatically generated by Utopia EDA
 * Generation started: 7-2-2023 0:51:36
 *
 * Ivannikov Institute for System Programming
 * of the Russian Academy of Sciences (ISP RAS)
 * 25 Alexander Solzhenitsyn st., Moscow, 109004, Russia
 * http://forge.ispras.ru/projects/utopia
 */

module delay_fixed_16_0_1_34(
	// inputs
	clock,
	reset,
	in,

	// outputs
	out
);


input clock;
input reset;
input [15:0] in;
output [15:0] out;
wire [15:0] in;
reg [15:0] out;
reg [31:0] state;
reg [31:0] s0;
reg [31:0] s1;
reg [31:0] s2;
always @(posedge clock) begin
if (!reset) begin
  state <= 0; end
else if (state == 0) begin
  state <= 1;
  s0 <= in; end
else if (state == 1) begin
  state <= 2;
  s1 <= s0; end
else if (state == 2) begin
  state <= 3;
  s2 <= s1; end
else begin
  state <= 0;
  out <= s2; end
end

endmodule // delay_fixed_16_0_1_34
/*
 * This Verilog library file was automatically generated by Utopia EDA
 * Generation started: 7-2-2023 0:51:36
 *
 * Ivannikov Institute for System Programming
 * of the Russian Academy of Sciences (ISP RAS)
 * 25 Alexander Solzhenitsyn st., Moscow, 109004, Russia
 * http://forge.ispras.ru/projects/utopia
 */

module sink_1x0(
	// inputs
	clock,
	reset,
	_dfc_wire_4873

	// outputs
);


input clock;
input reset;
input [15:0] _dfc_wire_4873;
wire [15:0] _dfc_wire_4873;

endmodule // sink_1x0
/*
 * This Verilog library file was automatically generated by Utopia EDA
 * Generation started: 7-2-2023 0:51:36
 *
 * Ivannikov Institute for System Programming
 * of the Russian Academy of Sciences (ISP RAS)
 * 25 Alexander Solzhenitsyn st., Moscow, 109004, Russia
 * http://forge.ispras.ru/projects/utopia
 */

module source_0x1(
	// inputs
	clock,
	reset,

	// outputs
	_dfc_wire_4853
);


input clock;
input reset;
output [15:0] _dfc_wire_4853;
wire [15:0] _dfc_wire_4853;

endmodule // source_0x1
