{{#LICENSE}}
{{!===---------------------------------------------------------------------===}}
{{!                                                                           }}
{{! Part of the Utopia HLS Project, under the Apache License v2.0             }}
{{! SPDX-License-Identifier: Apache-2.0                                       }}
{{! Copyright 2024 ISP RAS (http://www.ispras.ru)                             }}
{{!                                                                           }}
{{!===---------------------------------------------------------------------===}}
{{/LICENSE}}// This file has been automatically generated by Utopia HLS at {{GEN_TIME}}.
digraph {{KERNEL_NAME}} {
  {{#ELEMENTS}}{{NAME}} [shape={{SHAPE}}, label="{{LABEL}}"]
  {{#CONNECTIONS}}{{SRC_NAME}} -> {{TRG_NAME}} [label="{{CON_LABEL}}"]
  {{/CONNECTIONS}}
  {{/ELEMENTS}}
}
